### ISSUE TITLE
📎 Create CLI `explain` command

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1000]
### Description

This is going to be a command "a la' [man page](https://en.wikipedia.org/wiki/Man_page)".

The idea, for this initial implementation, is to have a way to provide documentation for our lint rules. 

```shell
biome explain noDebugger
```

This command will **render** the rule documentation in the terminal. This is similar to [`ruff rule` ocmmand](https://docs.astral.sh/ruff/configuration/#command-line-interface).

We already have a piece of code that collects the metadata from the rules, so we can copy and adapt the logic to what the command needs to do

https://github.com/biomejs/biome/blob/e980f76ffbf13a65bf125e4fa1606aaa5c9aea01/xtask/lintdoc/src/main.rs#L86-L130

I want to give this task to maintainers or new contributors who want to get familiar with the code base. This task **is not for beginners**.

Happy to answer any question!

**Comment by ematipico** [comment]
The command without options should not work or fall back to the help command.

Ideally this command will work with more things in the future, not just rules. I envision this command like a man page for biome

**Comment by ematipico** [comment]
I suggest looking at how we do things with other commands when we add new options. You should be able to use the structs of the rules (or the `Rules` struct) and theoretically bpaf should resolve the rule names as options

**Comment by kalleep** [comment]
Finally got some time to start some work on this. 

>You should be able to use the structs of the rules (or the Rules struct) and theoretically bpaf should resolve the rule names as options

Do you mean this [struct](https://github.com/biomejs/biome/blob/main/crates/biome_service/src/configuration/linter/rules.rs#L14) ? I don't see how I could use that structure to resolve positional arguments so I am a bit confused.

Just taking a `Vec<String>` and going through registries works but If this is to be used for other things that Lint rules in the future that wont work. So is the idea that if we have Something like `Option<Rules>` that one would only be set if a passed argument is a valid lint rule?

**Comment by ematipico** [comment]
Ah you’re right, the example that I suggested wouldn’t work. Although it would work if we decided to use only arguments without positional arguments:

```shell  
biome explain --no-debugger
```

**Comment by kalleep** [comment]
Yes that was what I thought first too but all rules also takes arguments `on|off|warn` so the way to use it like that would be e.g. `--no-debugger=off` and this structure only generates for Category `Lint` but not sure if that is a problem right now.

Two solutions I can come up with:
1. We take whatever we get as positional arguments and walk through registries and try to find metadata matching rules starting with js registry. If we have not found all rules specified we move of to json registry. I don't like this approach because if we want to add support for other stuff this probably would need a refactor.
2. We generate a new struct that can parse and validate positional arguments for rule. Then we could have what you suggested above. We could even collect and store metadata in this struct so the only thing we have to do in the explain command is format and print it.

**Comment by ematipico** [comment]
I lean more towards the second suggestion. It would require another `generate_` script (or modifying an existing one), but it's nothing we can't handle

**Comment by kalleep** [comment]
Got it working with the second approach. Just need to clean up a bit and format the the generated code :)
