### ISSUE TITLE
🐛 Quotes within quotes of Formatter IR isn't escaped

### ISSUE THREAD

**Issue by Yash-Singh1** [biomejs/biome#1056]
### Environment information

```block
This is running Biomejs playground with no special options enabled.
```

### What happened?

1. Had a string in Biome.js playground: https://biomejs.dev/playground/?code=YQB3AGEAaQB0ACAAIgBhACIAIAA%3D
```ts
await "a" 
```
3. Double quotes is not escaped or enclosing string is not single quoted (as in Prettier Formatter IR):
![Screenshot 2023-12-04 at 7 53 08 PM](https://github.com/biomejs/biome/assets/53054099/130828a8-d212-4305-9571-d1952d7b1d2d)
4. This also causes broken syntax highlighting

### Expected result

Expected result is either the double quotes surrounding `"a"` are escaped:

```ts
["await \"a\";", hard_line_break]
```

Or single quotes used for enclosing quotes instead:

```ts
['await "a";', hard_line_break]
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by yossydev** [comment]
@ematipico 
Thanks for your hard work! I have a question about this issue!
I'm looking at a lot of implementations right now, and the one that needs to be fixed is https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/src/js/expressions/await_ In the :expression.rs, am I correct? :eyes:.

**Comment by Yash-Singh1** [comment]
> @ematipico Thanks for your hard work! I have a question about this issue! I'm looking at a lot of implementations right now, and the one that needs to be fixed is https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/src/js/expressions/await_ In the :expression.rs, am I correct? 👀.

The bug is around how the formatter IR is stringified in the playground regardless of what the inputted code is. I think this will be somewhere in the playground packages, so you can start by bundling that and looking at how the WASM libraries run the actual Rust code. I went along that a bit and found the https://github.com/biomejs/biome/blob/75dacbb757d99b2420c7a44152ebcd32094845df/crates/biome_wasm/src/lib.rs#L98 function to be related.

**Comment by yossydev** [comment]
@Yash-Singh1 
Thanks for the advice!
I expected that there must be a further conversion process in getFormatterIr, so I went deeper and found the format_node, is this related...?

https://github.com/biomejs/biome/blob/75dacbb757d99b2420c7a44152ebcd32094845df/crates/biome_formatter/src/lib.rs#L1062-L1132

**Comment by ematipico** [comment]
Hi @Yash-Singh1 , apologies for let you stranded with this PR. 

The issue **isn't** related to the playground, it's related to our internal formatter.

First, head to `crates/biome_js_formatter/tests/quick_test.rs` and run the `quick_test` test. You might need to remove the `#[ignore]` macro and add the `-- --show-output` argument if you plan to run test from the CLI. If you use a IntelliJ IDE, you just run it from the UI and it should work.

Inside `src` put the code `await "a"` and the test should print the IR and the formatted code. You will notice that IR isn't correct.

How to debug it? Use the playground and inspect the CST. You will notice that it's a `JsAwaitExpression`. Then go in `biome_js_formatter/src/js` and look for `JsAwaitExpression` and eventually you will find the actual **implementation**, which is here:

[This is where we format the ](https://github.com/biomejs/biome/blob/7228fd1ec2cf5877cd6eebd9440f28862cf31644/crates/biome_js_formatter/src/js/expressions/await_expression.rs#L15)

It's possible that we aren't handled string literals correctly.

**Comment by ematipico** [comment]
Also, the expected result should be the same as prettier, so use prettier's IR as solution

**Comment by yossydev** [comment]
@ematipico 
Sorry, I'm sorry for all the explanations, but I felt I couldn't solve this problem myself...

I am very sorry, but I would like someone else to tackle this problem :pray:

**Comment by southball** [comment]
@ematipico (sorry for pinging, this is not urgent)

I have taken a look at the issue, and if there seems to be a solution I would like to try to implement it.

First of all, I think this would be a reasonable testcase to try to make pass:

```js
await "a";
await 'a';
await "'a'";
await '"a"';
f("a");
f('a');
f("'a'");
f('"a"');
```

https://biomejs.dev/playground/?code=YQB3AGEAaQB0ACAAIgBhACIAOwAKAGEAdwBhAGkAdAAgACcAYQAnADsACgBhAHcAYQBpAHQAIAAiACcAYQAnACIAOwAKAGEAdwBhAGkAdAAgACcAIgBhACIAJwA7AAoAZgAoACIAYQAiACkAOwAKAGYAKAAnAGEAJwApADsACgBmACgAIgAnAGEAJwAiACkAOwAKAGYAKAAnACIAYQAiACcAKQA7AA%3D%3D

There are two issues as you have mentioned:
1. String literals aren't formatted correctly
2. `await` literals do not emit the same IR as prettier. 

The second issue should be (I'm not sure) easier to solve, but the first issue isn't.

I have taken a look at the code and since the code formats correctly, I believe that the issue lies in the trait implementation of `std::fmt::Display` of `Document`. Digging deeper, I think this part of the code looks suspicious.

https://github.com/biomejs/biome/blob/789793506040e1018cdbeb5f27875e236266b192/crates/biome_formatter/src/format_element/document.rs#L237-L256

It seems that we are adding `StaticText("\"")`, `LocatedTokenText("\"a\"")`, `StaticText("\"")` to the buffer, and it is stored in a VecBuffer through the call to `biome_formatter::format!` which delegates to `biome_formatter::format`. We have then lost the context that `"a"` is nested in double quotes.

I am not so sure what we can do in order to fix this problem. Some potential solutions I can think of are

1. Introducing a new `FormatElement::String` variant that wraps a `Vec<FormatElement>` or `Box<[FormatElement]>` that represents strings wrapped in strings. This probably is not the solution as it would not be used outside IRs and also it would make invalid state like `FormatElement::String(Box::new([Tag(...)]))` representable.
2. Escape each text in `FormatElement::StaticText | FormatElement::DynamicText | FormatElement::LocatedTokenText` before passing it to `write_element`. This encodes the knowledge that these tokens are in text before passing them to the formatter, but I am not sure if this is correct.

Please kindly advise if there are any ideas, or feel free to take over the implementation.

**Comment by ematipico** [comment]
Thank you @southball for looking into this.

This is indeed a tricky issue, and you did a great job to narrow down the culprit!

Between the two solutions, my gut tells me to attempt the second solution, mostly because adding a new element to the IR might have more side-effects (memory, performance, etc.)

**Comment by southball** [comment]
Thank you!

I may have time to implement this at the end of this month / at the beginning of next month, so if anyone wants to send a PR please feel free to do so! Otherwise I will send a PR as soon as I can get to it!

**Comment by dyc3** [comment]
I'd like to give this a shot.
