### ISSUE TITLE
🐛 Extend is not working.

### ISSUE THREAD

**Issue by 0fatihyildiz** [biomejs/biome#1107]
### Environment information

```block
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

I get the biome configuration from `node_modules` but biome does not extend

```json
{
    "$schema": "https://biomejs.dev/schemas/1.4.0/schema.json",
    "extends": ["./node_modules/@somePackage/lint-frontend/biome.json"]
}
```

### Expected result

I expect the configuration to work, but the rules I set do not work.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Which package manager do you use?  @0fatihyildiz

**Comment by 0fatihyildiz** [comment]
> Which package manager do you use? @0fatihyildiz

I tried yarn and pnpm @ematipico

**Comment by ematipico** [comment]
So, that's the thing we warn users about. We don't have dependency resolution and we don't do fancy symbolic link resolution for now, so it won't work with pnpm because it creates symbolic links: https://biomejs.dev/reference/configuration/#extends



>     must exist in the file system;
>     are resolved from the path where the biome.json file is defined;
>     must be relative paths. Paths to libraries are not resolved;
>     must be reachable by Biome, e.g. symbolic links might not be resolved by Biome;
>     will be processed in order: from the first one to the last one;
>     can override the same properties, but ultimately only the last one will be used by Biome;

**Comment by 0fatihyildiz** [comment]
Yes I read this but I don't have any symbolic links in my use.

**Comment by ematipico** [comment]
If you can create a minimal reproduction, we could help.

**Comment by faultyserver** [comment]
> Yes I read this but I don't have any symbolic links in my use.

pnpm and Yarn (from version 3 and onward, at least) both default to using symbolic links to construct node_modules. There's a global store that caches dependencies, and then the `node_modules` folder is constructed by creating the necessary links to that store (which is great for disk space efficiency and other reasons, too).

Even if you don't have any symbolic links in your _project_, these package managers will most likely still be using symlinks (unless you have specifically, intentionally disabled it). You can check whether this is the case in a few ways:
- `ls -al node_modules` - will print out the list of all entries in the node_modules directory, and you'll likely see that they are all pointers to `node_modules/.pnpm/*` if you're using pnpm, or somewhere else if you're usying Yarn.
- `realpath node_modules/@somePackage/lint-frontend/biome.json` - will show the resolved path to this specific file. It likely will show you the same path to `node_modules/.pnpm/*`, meaning the file is a symbolic link.

If _neither_ of these are true, and you are certain that the file within your `node_modules` is _not_ a symbolic link, then we have a solid direction to investigate for a bug here. If it does end up being a symbolic link, then I believe this behavior is currently expected, since Biome doesn't traverse symlinks currently.

**Comment by ematipico** [comment]
@0fatihyildiz do you have any updates?

**Comment by 0fatihyildiz** [comment]
I'm a bit busy this week, but I'll prepare a reproduction.

**Comment by MohammedEsafi** [comment]
I have the same problem, I found that it works well with Biome CLI, but with the Biome extension in VSCode, it seems unable to read the extended rules

**Comment by ematipico** [comment]
We waited two weeks and we haven't received a reproduction. Please open a new issue if you arrive here, and attach a reproduction
