### ISSUE TITLE
📝 Multi-line formatting issue

### ISSUE THREAD

**Issue by AlexBlokh** [biomejs/biome#1218]
### Environment information

```bash
** from playground **
```

### Playground link

https://biomejs.dev/playground/?code=aQBtAHAAbwByAHQAIAB7ACAAZAByAGkAegB6AGwAZQAgAH0AIABmAHIAbwBtACAAIgBkAHIAaQB6AHoAbABlAC0AbwByAG0AIgA7AAoACgBjAG8AbgBzAHQAIABkAGIAIAA9ACAAZAByAGkAegB6AGwAZQAoACkAOwAKAAoAZABiAAoACgAuAHEAdQBlAHIAeQAKAAoALgB1AHMAZQByAHMACgAuAGYAaQBuAGQATQBhAG4AeQAoAHsACgAgACAAdwBoAGUAcgBlADoAewAKACAAIAAgACAAaQBkADoAIAAxADAACgAgACAAfQAKAH0AKQAKAA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by faultyserver** [comment]
I tool a look at this thinking it would be a relatively simple solve, but it turns out this is going to be pretty complicated to solve properly.

For anyone that wants to pick this up, the relevant content is in `crates/biome_js_formatter/src/utils/member_chain/chain_member.rs`. Right now, the member chain splits the groups of expressions at each Call expression (plus some extra logic), and then when formatting the whole chain it looks _behind_ the current group to see if there are empty lines that need to be preserved. This gets _close_ to Prettier, but doesn't account for a few other things that Prettier lets collapse. Prettier also looks _ahead_ so that only Call expressions can have empty lines after them, but Biome lets any expression have empty lines, leading to this specific behavior in this issue.

I think to solve this particular issue, there will need to be some changes to the hierarchy of formatting in the chain so that the current group can know if it's following a call expression, and also _potentially_ some changes to the grouping logic, though so far in my exploration that seems to match Prettier decently well.

Here's [Playground Link](https://biomejs.dev/playground/?indentStyle=space&code=LwAvACAATQBlAG0AYgBlAHIAIABjAGgAYQBpAG4AcwAgAHcAaQB0AGgAIABlAG0AcAB0AHkAIABsAGkAbgBlAHMAIABpAG4AIAB0AGgAZQAgAG0AaQBkAGQAbABlACAAcwBvAG0AZQB0AGkAbQBlAHMAIABjAG8AbABsAGEAcABzAGUAIABhAG4AZAAgAHMAbwBtAGUAdABpAG0AZQBzACAAZABvAG4AJwB0AC4ACgAKAC8ALwAgAFQAaABlAHMAZQAgAHMAaABvAHUAbABkACAAYQBsAGwAIABjAG8AbABsAGEAcABzAGUACgBmAG8AbwAKACAAIAAgACAALgBiAGEAcgAKACAAIAAKACAAIAAgACAALgBiAGEAegA7AAoAZgBvAG8ACgAgACAALgBiAGEAcgAKACAAIAAKACAAIAAuAGIAYQB6AAoAIAAgAAoAIAAgAC4AYgBhAHIAKAApAAoAZgBvAG8ACgAgACAACgAgACAALgBiAGEAcgAoACkACgAKACAAIAAgACAALgBiAGEAegA7AAoAZgBvAG8ACgAgACAACgAgACAALgBiAGEAcgBbADEAXQAKAAoAIAAgAC4AYgBhAHoAKAApADsACgBmAG8AbwAKACAAIAAKACAAIAAuAGIAYQByACgAKQAuAGIAYQB6AAoACgAuAGIAYQByACgAKQA7AAoAZgBvAG8ALgBiAGEAcgAKACAAIAAKACAAIAAuAGIAYQB6ACgAKQAKACAAIAAuAGIAYQByAAoAIAAgAAoAIAAgAC4AYgBhAHoAKAApADsACgBmAG8AbwAKACAAIAAKACAAIABbADEAXQAKACAAIAAKACAAIAAuAGIAYQByACgAKQA7AAoAZgBvAG8ACgAgACAACgAgACAALgBiAGEAcgAKACAAIAAKACAAIABbADEAXQAKACAAIAAKACAAIAAuAGIAYQByACgAKQA7AAoACgAvAC8AIABUAGgAZQBzAGUAIABzAGgAbwB1AGwAZAAgAGEAbABsACAAcAByAGUAcwBlAHIAdgBlACAAZQBtAHAAdAB5ACAAbABpAG4AZQBzACAAaQBuACAAcwBvAG0AZQAgAHcAYQB5AAoACgBmAG8AbwAuAGIAYQByACgAKQAKACAAIAAKACAAIAAuAGIAYQB6ACgAKQA7AAoAZgBvAG8AIAAuAGIAYQByACgAKQAKACAAIAAKACAAIAAuAGIAYQB6AC4AYgBhAHIAKAApADsACgBmAG8AbwAKAAoALgBiAGEAcgAoACkACgAgACAAIAAgAAoAIAAgAC4AYgBhAHoAKAApADsACgAKAGYAbwBvAAoACgAuAGIAYQByAC4AdwBoAGEAdAAoACkALgBmAG8AbwAKACAAIAAuAHcAaABhAHQAKAApAAoAIAAgACAAIAAKACAAIAAuAGIAYQB6ACgAKQA7AAoAZgBvAG8ALgBiAGEAcgAKACAAIAAKACAAIAAuAGIAYQB6ACgAKQAKACAAIAAKACAAIAAuAGIAYQByAAoAIAAgAC4AYgBhAHoAKAApAAoAIAAgAAoAIAAgAC4AZgBvAG8AKAApADsACgAKAA%3D%3D) with a variety of test cases to check for completeness.
