### ISSUE TITLE
Add support for `biome.jsonc`

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1259]
### Description

From https://github.com/biomejs/biome/discussions/282

We want to resolve `biome.jsonc` too.

The project should error if both files are found

**Comment by giacomorebonato** [comment]
The terse syntax of `biome.json5` would be nice as well. 
`.jsonc` is also great anyway, thanks!

**Comment by ematipico** [comment]
> The terse syntax of `biome.json5` would be nice as well. 
> `.jsonc` is also great anyway, thanks!

Unfortunately Biome doesn't support the `json5` file extensios. Do you know if they have differences in their grammar?

**Comment by Conaclos** [comment]
There are [many differences](https://json5.org/). For example JSON5 allows unquoted properties, single quoted strings, hexadecimal numbers, NaN, Infinity constants, ...

There are many competing standards out there: [JSON5](https://json5.org/), [JSON6](https://github.com/d3x0r/JSON6#json6--json-for-humans), [HJSON](https://hjson.github.io/). They don't seem to be as widespread as JSONC.

**Comment by giacomorebonato** [comment]
How do you measure the popularity of JSON5 vs JSONC?

This chart on NPM shows an higher use of JSON5 parser:
https://npmtrends.com/hjson-vs-json5-vs-jsonc-parser-vs-relaxed-json

Also: 

> Chromium uses JSON5 for internal configs, e.g. [runtime_enabled_features.json5](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/runtime_enabled_features.json5).
Craft elaborately sequenced animation timelines using [ProStyle](https://prostyle.io/). Write your stories in a declarative JSON5 syntax and ProStyle will generate the web content and scripts that animate it. ([examples](http://codepen.io/garyc/))
A web-based [JSON-to-CSV converter](https://konklone.io/json/). The application is [open source](https://github.com/konklone/json/), and conversion is performed in the browser and data is never uploaded to a server.
WebStorm natively supports [JSON5](https://www.jetbrains.com/help/webstorm/json.html).

Taken from https://github.com/json5/json5/wiki/In-The-Wild#apps

Since both JSONC and JSON5 have valid JS syntax, hence Biome knows it, I wish they could be both supported.

**Comment by ematipico** [comment]
@giacomorebonato 

If you're interested, you can try creating a parser using our infrastructure, and we can evaluate its inclusion.

JSON5 is outside our roadmap and interests, so I don't think we have the capacity to help you.

**Comment by Conaclos** [comment]
> This chart on NPM shows an higher use of JSON5 parser:
> https://npmtrends.com/hjson-vs-json5-vs-jsonc-parser-vs-relaxed-json

It is really easy to support JSONC in an existing JSON parser, because all you have to do is comments and trailing comma handling. So it is not surprising that few people use the jsonc parser directly. I was not aware of its existence.

> How do you measure the popularity of JSON5 vs JSONC?

Mostly of experience.
Most of the configurations I am aware of use JSONC (`tsconfig.json`, vscode configurations, ...).

If I search for all files using `jsonc` on GitHub extension I found [32k files](https://github.com/search?q=path%3A*.jsonc&type=code). However, this doesn't take JSONC files using `.json` extensions such as `tsconfig.json` ([930k files](https://github.com/search?q=path%3Atsconfig.json&type=code)), vscode configs ([31k files](https://github.com/search?q=path%3A.vscode%2F**%2F*.json&type=code)), and so on.
With a pessimistic measure we are already to more than 1M files using JSONC on GitHub.

[33k files](https://github.com/search?q=path%3A*.json5&type=code) use the JSON5 extension.

**Comment by Eutropios** [comment]
Came here looking for this issue before opening one of my own.

I'd imagine that implementing a linter/formatter for `JSONC` (json w/ comments) would be significantly easier than an implementation for `JSON5`, `JSON6`, and `HJSON` due to the numerous additions in each format. I'd also imagine that extending this further to [`YAML 1.2`](https://github.com/yaml/yaml-spec) (a strict-superset of `JSON`) and Google's DSL [`jsonnet`](https://github.com/google/jsonnet) would be out of scope for this project.

I'm unsure if this could be of any help to whomever implements this parser, but the [neovim implementation of treesitter](https://github.com/nvim-treesitter/nvim-treesitter) has a parser for `JSONC` which can be found [here](https://gitlab.com/WhyNotHugo/tree-sitter-jsonc). It also has parsers for `JSON5`, `HJSON`, `jsonnet`, and `YAML`.

Looking forward to what this project has in store for the future. Keep up the good work!

**Comment by lgarron** [comment]
I'd also like to put in a word for supporting JSON5 and ideally recommending it over JSONC if you have a choice between the two. There are a few good reasons mentioned in https://github.com/microsoft/vscode/issues/100688#issuecomment-720321970 but the main one is:

> There is **no standard of JSONC**, just conventions. However, JSON5 is a format with spec.

JSONC is a bit of a liability as a result: feature set/compatibility/conformance/security/etc.

Since JSONC support is new for Biome, it's possible to make a more future-proof choice.

**Comment by Malix-off** [comment]
Same recommendation for me: `json5` > `jsonc`
