### ISSUE TITLE
A semicolon is accidentally removed

### ISSUE THREAD

**Issue by m-shaka** [biomejs/biome#1356]
### Environment information

```bash
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.14.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.7.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              true
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
	"$schema": "https://biomejs.dev/schemas/1.4.1/schema.json",
	"organizeImports": {
		"enabled": true
	},
	"linter": {
		"enabled": false,
		"rules": {
			"recommended": true
		}
	},
	"files": {
		"include": [
			"**/*.ts"
		]
	},
	"formatter": {
		"enabled": true
	},
	"javascript": {
		"formatter": {
			"lineWidth": 40,
			"semicolons": "asNeeded"
		}
	}
}
```

### Playground link

https://biomejs.dev/playground/?lineWidth=40&semicolons=as-needed&enabledLinting=false&importSortingEnabled=false&code=ZgB1AG4AYwB0AGkAbwBuACAAZgB1AG4APABUAD4AKAAKAAkAZgBuADoAIAAoAGEAcgBnAHMAOgAgAHsACgAJAAkAYQA6ACAAcwB0AHIAaQBuAGcACgAJAAkAYgA6ACAAcwB0AHIAaQBuAGcACgAJAH0AKQAgAD0APgAgAHYAbwBpAGQALAAKACkAIAB7AAoACQBmAG4AKAB7ACAAYQA6ACAAIgBhACIALAAgAGIAOgAgACIAYgAiACAAfQApAAoAfQAKAAoAZgB1AG4AKAAoAGEAcgBnAHMAOgAgAHsAIABhADoAIABzAHQAcgBpAG4AZwA7ACAAYgA6ACAAcwB0AHIAaQBuAGcAIAB9ACkAIAA9AD4AIAB7AAoACQByAGUAdAB1AHIAbgAgAGEAcgBnAHMACgB9ACkACgA%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### Description
`fun((args: { a: string; b: string }) => {` is formatted to `fun((args: { a: string b: string }) => {`, which is syntactically broken.
`lineWidth` setting is 40 and the length of this line is 41. If you rename `args` to a shorter name like `obj`, the semicolon won't be removed. If you rename it to a longer name, the line will be line-wrapped.

**Comment by faultyserver** [comment]
Minimal repro. Semicolons must be set to `asNeeded`:

```typescript
const a: {
    a: string;
    b: string;
} = 1;

// Biome output
const a: {
    a: string
    b: string
} = 1
```

[Playground Link](https://biomejs.dev/playground/?code=YwBvAG4AcwB0ACAAYQA6ACAAewAKACAAIAAgACAAYQA6ACAAcwB0AHIAaQBuAGcACgAgACAAIAAgAGIAOgAgAHMAdAByAGkAbgBnAAoAfQAgAD0AIAAxADsA)

**Comment by faultyserver** [comment]
Actually, it looks like [Prettier has the same output](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDJngA6UmJOeGATgJZQDmA3EaZgEbkzV2NQC+mAvJgCM9EABoQEAA4wq6ZKGwUKEAO4AFJQjTIQ2ADarsATx0SWFbGADWcGAGVsAWzgAZGnGQcArnHOWbO3spKxpaZAAzAzQ-EBinKkjo2LgADyk4ahdYAwAVTKglKjgdJCj9GIk0MP04AEVvCHgkitiAKzRU+xr6xuay5IkARz64dRUpUr00AFooODgAEyXxEA5sKn0wgGEIJydsXQN9Veq6WoBBGA4qFm94dUz3eZbKkAALGCd9AHV3qngaBCYDg9m0AKoADcAcZdGA0GYQJDfABJKDLWD2MDUGQXdH2GDGWqvWJSFQxH6WKS6MklTKQzwSGgxCgwcbYWgHEkSEIUFm6QkZNDYqgyVYUOAjKgS9mcw4DVoSbwxXLYFilcpvOBOFhLZaLVzYOjeDlwABiEAoB2uYSO9wgqxgap+VEWMHeyAALBIwN4+ZaAPIRCIxGDIGZCHmcGAut0epAADgArDweEA), and the [typescript playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABKMAeAKgPgBQCgCQwYAXItgIYBOA5gM6kDeB+5ptUlMY1zARmxy498AXwCUiALyZEANzgwAJgBpcEpoTDYGiVogBE5fcsT8DvfYnG4RuXCjz4KNeoh172nbgG5TAr9RWEtJuzJQAplAglEhUdAQiqmK4QA) is also okay with leaving these semicolons out, so I believe this behavior is actually expected (though it's surprising to me, as well. I would've assumed it was invalid).

Because this output matches Prettier and is valid TypeScript, I'm going to say this is not a bug when `"semicolons": "asNeeded"` is set. If you are seeing this issue without that setting, or if it is causing parsing/compilation errors, then we can investigate more and also open an issue with Prettier to address it cohesively.

**Comment by m-shaka** [comment]
Thank you for your quick fix! @faultyserver
