### ISSUE TITLE
🐛 Some ignore pattern generate `ignored file` error

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1471]
### Environment information

```block
CLI:
  Version:                      1.5.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.5.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.5"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

Execute the following script and observe the error:

```shell
$ git clone https://github.com/bare-ts/bare.git
$ cd bare
$ npm ci
$ npx biome format --verbose --error-on-warnings --diagnostic-level=warn .
./tests-corpus/index.test.js format ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ The file ./tests-corpus/index.test.js was ignored.
  

Compared 20 file(s) in 7ms
Skipped 1 file(s)
```

The configuration is:

```jsonc
{
  "files": {
    "ignoreUnknown": true
  },
  "formatter": {
    "indentStyle": "space",
    "ignore": ["./tests-corpus/*"]
  },
  "vcs": {
    "enabled": true,
    "clientKind": "git",
    "
  }
}
```

If I change `formatter.ignore` from `./tests-corpus/*` to `./tests-corpus` the bug seems fixed.

### Expected result

No error should be thrown.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by blutorange** [comment]
With version 1.4.1 I had

```json
  "files": {
    "ignore": ["localization.ts"]
  }
```

After updating to version 1.5.0, it did not ignore the file anymore, reporting lint errors in that file. After I changed the ignore pattern to `**/localization.ts`, it ignores the file again, but now prints

```
[widget-common]: src/js/localization.ts lint ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[widget-common]: 
[widget-common]:   × The file src/js/localization.ts was ignored.
```

The exit code is still `0`, so the lint is successful.

**Comment by notramo** [comment]
This is very confusing for junior devs. In a rare case when setting up a linter can decrease productivity instead of increasing it.

Seriously, what is the logic behind these huge warnings? These are not accidental ignores, the paths are explicitly ignored in the config. Imagine if Git was printing after every pull/push/merge/commit/etc this:
```
Warning: node_modules/ is ignored.
Warning: .svelte-kit/ is ignored.
Warning: .vite.config.ts-timestamp-xyz is ignored.
...
```

**Comment by ematipico** [comment]
@notramo 

The reason why you see more diagnostics than before is because we had reports where users didn't understand why certain files weren't checked.

Even though we document that on our website, the reports were still coming.

Given the previous statement, and given that now you see too many diagnostics, what do you think we should do? What do you suggest?

**Comment by notramo** [comment]
If the `assets/do-not-modify.json` is ignored, and Biome receives `assets/do-not-modify.json` explicitly, then show the warning, but if receives `assets/`, then do not.
But even in this case, it can be useful, so I'm not sure if it should be implemented.

However, there is an use case where the current behavior is problematic. When used with [lefthook](https://github.com/evilmartians/lefthook), it's simpler to not copy the entire ignore list from `biome.json` to `lefthook.yml`.
```
biome:
    glob: 'assets/js/**.{ts,json,js}'
    run: bun run biome check --apply {staged_files}
```
For this use case I would recommend adding `--no-ignored-file-warning`.

**Comment by gunta** [comment]
So how do we ignore those warnings?

**Comment by ematipico** [comment]
They are harmless. Use `--diagnostic-level=error` to show only the ones with error severity

**Comment by jschaf** [comment]
> They are harmless. Use --diagnostic-level=error to show only the ones with error severity

I'm unable to silence these warnings. The `format` command doesn't support `--no-ignored-file-warning`

```ts
# *.pb.ts is ignored
biome format --diagnostic-level=error .     
./google/type/money.pb.ts format ━━━━━━━━━━━━

  ✖ The file ./google/type/money.pb.ts was ignored.
```

> The reason why you see more diagnostics than before is because we had reports where users didn't understand why certain files weren't checked.
>
> Given the previous statement, and given that now you see too many diagnostics, what do you think we should do? What do you suggest?

I expect linters to output nothing or a short success message if there are no errors. If I wanted to figure out why biome was ignoring files, I'd first look to increase the log level to DEBUG.

I think emitting warnings is a short-term solution. Most folks will turn them off because it's too noisy. Once the warnings are disabled, we're at the same staring point. In the long term, users still won't understand why biome is ignoring files since they'll have the warnings disabled.

Since the problem is that users don't understand why biome ignores files and open support tickets, maybe this can be solved in the ticket template?

**Comment by Conaclos** [comment]
This should be fixed in the last patch release (v1.5.1). Could anyone confirm that they no longer get errors?

**Comment by notramo** [comment]
Tested on 1 project, it's fixed for our use case.

**Comment by przemyslawzalewski** [comment]
I can confirm the latest patch resolves the issue for us, thanks! ❤️

**Comment by longhoccongnghe** [comment]
Sorry, I configured as below and when I run yarn biome lint, files and subfolders in src/common are not ignored? Is anyone having the same problem?
```
{
  "$schema": "https://biomejs.dev/schemas/1.8.2/schema.json",
  "files": {
    "ignore": ["dist/**", "node_modules/**", ".vscode/**", "scr/common/**"]
  },
  "organizeImports": {
    "enabled": true
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true
    }
  },
  "formatter": {
    "enabled": true,
    "indentWidth": 2,
    "indentStyle": "space",
    "formatWithErrors": true
  }
}

```

**Comment by Sec-ant** [comment]
> Sorry, I configured as below and when I run yarn biome lint, files and subfolders in src/common are not ignored? Is anyone having the same problem?

`"scr/common/**"` -> `"src/common/**"`

**Comment by longhoccongnghe** [comment]
@Sec-ant Oh thanks you so much

**Comment by leo-longtran** [comment]
@Sec-ant Any way, I don't want to ignore the file in `biome.json`, but I want to comment right in that file, but currently I only know the comment `// biome-ignore lint/suspicious/noExplicitAny: <explanation>` to ignore a line, how do can I ignore biome check in the entire file by commenting. Many thanks

**Comment by ematipico** [comment]
> how do can I ignore biome check in the entire file by commenting.
That's a feature we don't have yet

**Comment by leo-longtran** [comment]
Here is my problem
Currently I am configuring as below in the `biome.json` file
```
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true
    },
    "include": ["src/**", "tests/**"],
    "ignore": ["src/common/**"]
  }
```
If I run the command `yarn biome lint` on the terminal there is no problem. But I want to set up a `pre-commit` with husky, I will run the command `yarn biome lint` to make sure what I commit is valid, however if I edit any file outside the src `folder` or `tests` it will lead to an error. The path was not found because the `yarn biome lint` command ignored it. Do you have any suggestions to solve this problem?

**Comment by ematipico** [comment]
You can use `--no-errors-on-unmatched`.

Next time you can consult the CLI reference page: https://biomejs.dev/reference/cli/#biome-lint

**Comment by Christopher-Hayes** [comment]
```json
"linter": {
  "include": []
}
```

Is the wrong rule name btw. It's "includes" with an "s". Biome doesn't seem to have an "ignore" anymore. But, if you just type something like `"!file.css"` in the includes, it will ignore that file.

Alternatively, there's also the general `{ "files": { "includes": [] } }`
docs: https://biomejs.dev/reference/configuration/#filesincludes
