### ISSUE TITLE
🐛 Import sorting breaks when a copyright comment is present

### ISSUE THREAD

**Issue by Reed-Anderson** [biomejs/biome#1563]
### Environment information

```block
CLI:
  Version:                      1.5.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.6.6"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

When Biome sorts an import line to be first, that line will be place above any comments which precede the imports.

This:
```
/*******************************************************************************
 * 
 * @copyright <Company>
 * 
 ******************************************************************************/
import { useState } from "react"
import { TextInput, TextInputProps } from "./textInput"
import classNames from "classnames"
```

Becomes this
```
import classNames from "classnames"
/*******************************************************************************
 * 
 * @copyright <Company>
 * 
 ******************************************************************************/
import { useState } from "react"
import { TextInput, TextInputProps } from "./textInput"
```
(Reproducible in the Playground)

### Expected result

```
/*******************************************************************************
 * 
 * @copyright <Company>
 * 
 ******************************************************************************/
import classNames from "classnames"
import { useState } from "react"
import { TextInput, TextInputProps } from "./textInput"
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment]
I have to say I think Biome’s behavior makes more sense for comments in general, even though I agree “file header comments” such as copyright notices may be the exception.

I suppose Biome could try to be even more clever by looking at the contents of the comment, but it becomes a bit of a slippery slope of how much assumptions you want to make. What if someone just left the comment to highlight the license of the library they’re importing?

As a workaround, would it be possible to insert a newline between your copyright notices and the import statements? I would expect this issue to be resolved that way.

**Comment by arendjr** [comment]
> we could check if the import is the first statement of the file.

That has its downsides too…

```ts
// Must be imported first.
import “./polyfills”;
import “../node_modules/material-ui/dist/styles.css”;
```

**Comment by Conaclos** [comment]
Yes, however, most of the time the first comment is a copyright notice. I am not sure if it is usual of attaching comments to import statements...

**Comment by arendjr** [comment]
I guess it depends on the codebase. Most codebases I work with don’t have copyright notices in individual files, though occasionally they’ll have a notice saying the file is generated or some other explanation. Those we’d all like to keep at the top.

But I also know of comments that describe why `redux-toolkit/dist/some/inner/path` was imported rather than importing from the toplevel, for instance.

Generally I would actually agree that most top-level comments should indeed stay there, but at the same time I usually see the ones that are true “top-level comments” are commonly separated with a newline from the imports, whereas the ones that actually do indeed explain something about an import statement aren’t separated.

**Comment by Conaclos** [comment]
You are right, most of the copyright notice are separated from imports with a newline.

Another possibility is to make an exception for comments that spread on several lines.

**Comment by ematipico** [comment]
We don't have the means to know when a multi line comment is a copyright or not, if a top level comment or not. We don't even know what's copyright because every company does it differently.

While I understand the sentiment to try our best here, I don't see enough value trying to solve this situation that can't be solved without too much effort. The user can simply add a new line to solve the problem.

**Comment by arendjr** [comment]
Agreed @ematipico. Closing then, and our recommendation is to use a newline between the notice and the imports.
