### ISSUE TITLE
💅 generic function with any parameters

### ISSUE THREAD

**Issue by hanako-eo** [biomejs/biome#1882]
### Environment information

```bash
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

lint/suspicious/noExplicitAny

### Playground link

https://biomejs.dev/playground/?code=ZgB1AG4AYwB0AGkAbwBuACAAZgBvAG8APAAKACAAIAAgACAAVAAgAGUAeAB0AGUAbgBkAHMAIABSAGUAYwBvAHIAZAA8AHMAdAByAGkAbgBnACwAIAAoAC4ALgAuAGEAcgBnAHMAOgAgAEEAcgByAGEAeQA8AGEAbgB5AD4AKQAgAD0APgAgAHUAbgBrAG4AbwB3AG4APgAsAAoAPgAoAGYAdQBuAGMAdABpAG8AbgBzADoAIABUACkAOgAgAFQAIAB7AAoAIAAgACAAIAByAGUAdAB1AHIAbgAgAGYAdQBuAGMAdABpAG8AbgBzAAoAfQA%3D

### Expected result

In this case, I expect no errors on the generic or to be able to dissociate it with a commentary.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
You could use `unknown` here?

**Comment by hanako-eo** [comment]
I cannot use unknown in the Array or instead for the array because I use in another part of my project `Parameters<T[K]>`.

The file where you can find the code and see the error it can give : https://github.com/hanako-eo/neige/blob/main/packages/http/src/ffi.ts

**Comment by hanako-eo** [comment]
for `never` it works (which seems a bit odd to me, but I'm not going to complain) and I'm well aware that the use of `any` can be dangerous, but it's one of the rare cases where `any` really reflects the type of give. And in this case, if I replace the `any` with `never` I've got a semantic problem, even if in fact it works, `never` doesn't mean that, it's misused. I would have liked to use `Function` but it doesn't have the same meaning as `(...args: any) => any` for TypeScript (and I understand why) and I think the only way to describe any function while remaining flexible is with `(...args: any) => any` and `any`. I share your opinion on the unsafety of `any` but without losing the semantics, it seems sensible to me to use `any`. (I don't know if I've made myself clear enough ^^', sorry if I haven't)

**Comment by Conaclos** [comment]
> for never it works (which seems a bit odd to me, but I'm not going to complain)

It is not so easy to get because you dive into type realm.

`never` is a subtype of all types, also called the [bottom type](https://en.wikipedia.org/wiki/Bottom_type).
`unknown` is a super-type of all types, also called the [top type](https://en.wikipedia.org/wiki/Top_type).
`any` is any type.

For type safety, you have to use `unknown` or `never` where appropriate.
This depends on [type variance](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)).
Basically if you expect a function `(B) => A` and `B` is a subtype of `A`, then you can use a function `(A) => B`.
The return type is covariant, and the parameter type is contravariant.

Let's take an example:

```ts
class Entity {
  constructor(readonly name: string) {}
}
class B extends Person {
  constructor(name: string, readonly age: number) { super(name); }
}

declare let f: (b: Person) => string;
declare let g: (b: Entity) => string;

// valid because `g` expects an`Entity` and `f` ensures to provide a `Person` that is a subtype
f = g;
f(new Person("anonymous". 30));

// invalid because `f` expects a`Person` and `f` doesn't ensure that
g = f; // compile error
g(new Entity("entity"));
```

In your case you just say that T is a subtype of (extends) `(...args: never[]) => unknown`, meaning that you accept a function with a return type that is a subtype of `unknown` and the type of the parameters that are a super-type of `never`.

`never` is the safe choice here.

I think we could improve the rule to propose `never` when it makes sense.

**Comment by hanako-eo** [comment]
Ok, I see. Variance isn't a subject I've mastered to perfection yet, I'm familiar with it in Rust, but I've never seen it in TypeScript. Or maybe I just haven't made the mental connection yet. It still disturbs me a bit to have to use never because even though I understand what you're saying, I really have the impression that never isn't made for that.
