### ISSUE TITLE
🐛 Providing `--config-path` changes cwd for `"extends"` module resolving

### ISSUE THREAD

**Issue by domin-mnd** [biomejs/biome#2231]
### Environment information

```block
CLI:
  Version:                      1.6.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v21.6.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

1. Create a config file in a different from cwd location e.g. `config/biome.json`
2. Add config content with the usage of `"extends"` utilizing package module resolving e.g.
```json
{
  "extends": ["@domin-mnd/config/biome"]
}
```
3. Run `biome lint . --config-path config`
4. ![image](https://github.com/biomejs/biome/assets/69919939/c0f60758-4794-4a98-92dd-39de8e1f074b)

> [!NOTE]
> [MRE CBS](https://codesandbox.io/p/sandbox/runtime-microservice-ygrpgx)

### Expected result

Resolve module from the working directory location where `biome lint` is executed

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment]
This might be a regression of #2160. When biome is used as a language server, the `cwd` will hold the editor's path dir as its value, making it impossible to resolve external packages. That's why #2160 tries to use the config dir as the root for resolution.

I can come up with 2 options:

1. Use `cwd` when `--config-path` flag is used.
2. Add a fallback mechanism to resolve in `cwd`.
