### ISSUE TITLE
📎  Implement`useConsistentNewBuiltin` - `unicorn/new-for-builtins` 

### ISSUE THREAD

**Issue by minht11** [biomejs/biome#2539]
### Description

Implement [unicorn/new-for-builtins](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/new-for-builtins.md)

**Comment by minht11** [comment]
I will try to work on it myself.

**Comment by Conaclos** [comment]
Note that `new Symbol` and `new BigInt` are already forbidden by [noInvalidNewBuiltin](https://biomejs.dev/linter/rules/no-invalid-new-builtin/).
Thus, this rule should not cover these two cases.

Also, I propose a more consistent name with our existing rules: `useConsistentNewBuiltin`.

**Comment by ematipico** [comment]
Why "Consistent" @Conaclos ? I think `useNewBuiltin` is enough.

**Comment by Conaclos** [comment]
Taking a closer look at the rule, the following constructors cannot be instantiated without `new`.

- ArrayBuffer
- BigInt64Array
- BigUint64Array
- DataView
- FinalizationRegistry
- Float32Array
- Float64Array
- Int16Array
- Int32Array
- Int8Array
- Promise
- Proxy
- Set
- SharedArrayBuffer
- Uint16Array
- Uint32Array
- Uint8Array
- Uint8ClampedArray
- WeakMap
- WeakRef
- WeakSet

Since we have [noInvalidNewBuiltin](https://biomejs.dev/linter/rules/no-invalid-new-builtin/), we should certainly have something like `noInvalidBuiltinInstatiation`.
**However, I doubt the usefulness of having three rules.**
I think we could deprecate [noInvalidNewBuiltin](https://biomejs.dev/linter/rules/no-invalid-new-builtin/) and simply handle `Symbol` and `BigInt` in `useConsistentNewBuiltin`.

Any opinion?

> Why "Consistent" @Conaclos ? I think useNewBuiltin is enough.

Became I was thinking about `useConsistentBuiltinInstatiation`.
You are right we should certainly use `useConsistentBuiltinInstatiation` or `useNewBuiltin`.
Any preference?

**Comment by Conaclos** [comment]
Alternatively we could deprecate [noInvalidNewBuiltin](https://biomejs.dev/linter/rules/no-invalid-new-builtin/) and create two rules: `useConsistentBuiltinInstatiation` and `noInvalidBuiltinInstatiation`.

**Comment by minht11** [comment]
I slightly prefer `useConsistentBuiltinInstatiation` even if it is bit long, since rule as it currently is dissallows use of new keyword in some cases, so it is bit more clear. [noInvalidNewBuiltin](https://biomejs.dev/linter/rules/no-invalid-new-builtin/) deprecation also makes sense to me since they effetively do the same thing, but I will wait for confirmation before renaming things.
