### ISSUE TITLE
📎  Implement selector-type-no-unknown

### ISSUE THREAD

**Issue by vasucp1207** [biomejs/biome#2543]

**Comment by Kazuhiro-Mimaki** [comment]
I'm interested in tackling this issue.

**Comment by Kazuhiro-Mimaki** [comment]
I'm interested in tackling this issue 🦀

**Comment by Kazuhiro-Mimaki** [comment]
@togami2864 
Do you mean it would be better to implement the options?

**Comment by togami2864** [comment]
@Kazuhiro-Mimaki 
I meant that it would be better for the default behavior of Biome to mimic that of 'stylelint' when used the following options 
```
module.exports = {
	rules: {
		'selector-type-no-unknown': [
			true,
			{
				ignore: ['custom-elements'],
			},
		],
	},
};
```
rather than the default behavior of 'stylelint' with no options.
I think it's beneficial to be able to use these by simply running 'biome init', without the need to add any configuration.

**Comment by Kazuhiro-Mimaki** [comment]
I understood, thank you for your detailed explanation.
