### ISSUE TITLE
📎 Implement `noLabelWithoutControl` - `jsx-a11y/label-has-associated-control`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#2610]
### Description

Implement [label-has-associated-control](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-associated-control.md).

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

Suggested name: `noLabelWithoutControl`

**Comment by mdm317** [comment]
May i try this?

**Comment by ematipico** [comment]
One thing we need to deviate from the rule, is to also support the attribute `for`.

The attribute `htmlFor` is react specific, but we should be more broad because other libraries such as preact and solid support the `for` attribute.

**Comment by mdm317** [comment]
Thank you for letting me know.
I looked into applying this rule to `preact` and `solid`, but it seems too difficult for me to handle.
I'll look for other issues I can contribute to.

**Comment by michellocana** [comment]
Can I get this one? :)

**Comment by michellocana** [comment]
This rule also have some options:
* `labelComponents` - [used less than 1k times](https://github.com/search?q=path%3A.eslintrc*+label-has-associated-control+labelComponents&type=code)
* `labelAttributes` - [used 1.2k times](https://github.com/search?q=path%3A.eslintrc*+label-has-associated-control+labelAttributes&type=code)
* `controlComponents` - [used 1.8k times](https://github.com/search?q=path%3A.eslintrc*+label-has-associated-control+controlComponents&type=code)
* `assert` - [used 1.8k times](https://github.com/search?q=path%3A.eslintrc*+label-has-associated-control+assert&type=code), but rarely with a value other than "either", which is the default
* `depth` - [used 1.2k times](https://github.com/search?q=path%3A.eslintrc*+label-has-associated-control+depth&type=code)

In my opinion we should implement the first 3, because it gives the user more control over cases the rule won't error by default. 
The `assert` option might not be needed as few people are using it without the default behavior. 
I'm not so sure about the `depth` option, the original rule accepts a max value of `25`, I don't see too much harm on having this depth by default, but I might be wrong here, let me know 👀.
