### ISSUE TITLE
Indentation of nested template strings is broken

### ISSUE THREAD

**Issue by craftedsystems** [biomejs/biome#3030]
### Environment information

```bash
(playground link only)
```

### Playground link

https://biomejs.dev/playground/?code=ZgB1AG4AYwB0AGkAbwBuACAAcgBlAG4AZABlAHIAKAApACAAewAgACAACgAgACAAcgBlAHQAdQByAG4AIABoAHQAbQBsAGAACgAgACAAIAAgADwAZABpAHYAIABjAGwAYQBzAHMAPQAiAGEAYwBjAG8AdQBuAHQAIgA%2BAAoAIAAgACAAIAAgACAAPABoADEAPgBBAGMAYwBvAHUAbgB0ADwALwBoADEAPgAKACAAIAAgACAAIAAgADwAZABpAHYAIABjAGwAYQBzAHMAPQAiAGkAYwBvAG4AIgA%2BAAoAIAAgACAAIAAgACAAIAAgADwAdQBpAC0AYwBoAGUAdgByAG8AbgAtAGEAcgByAG8AdwAtAGkAYwBvAG4APgA8AC8AdQBpAC0AYwBoAGUAdgByAG8AbgAtAGEAcgByAG8AdwAtAGkAYwBvAG4APgAKACAAIAAgACAAIAAgADwALwBkAGkAdgA%2BAAoAIAAgACAAIAAgACAAJAB7AAoAIAAgACAAIAAgACAAIAAgAGYAZQBhAHQAdQByAGUARgBsAGEAZwAuAHMAaABvAHcAQQBCAEMAKAApAAoAIAAgACAAIAAgACAAIAAgACAAIAA%2FACAAaAB0AG0AbABgAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgADwAdQBpAC0AYgB1AHQAdABvAG4AIABjAGwAYQBzAHMAPQAiAHMAZQBjAG8AbgBkAGEAcgB5ACIAIABAAGMAbABpAGMAawA9ACQAewB0AGgAaQBzAC4AXwBuAGEAdgBpAGcAYQB0AGUAVABvAEEAQgBDAH0APgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJAB7AHQAaABpAHMALgAkAHQALgBnAGUAdAAoACcAYgBhAHMAZQAuAEEAQgBDACcAKQB9AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgADwALwB1AGkALQBiAHUAdAB0AG8AbgA%2BAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAYAAKACAAIAAgACAAIAAgACAAIAAgACAAOgAgAG4AbwB0AGgAaQBuAGcACgAgACAAIAAgACAAIAB9AAoAIAAgACAAIAA8AC8AZABpAHYAPgAKACAAIABgADsACgB9AAoA

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by craftedsystems** [comment]
Prettier can handle this:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEATggCZyEAUAlPsPvgDpT3EzqHMAWMAtgDYADJvXoAeEjgBu+MHwCGAZwUBeBiDlhImGGoB8wkWM4BGXQEFNEbaID0J-c0P5xUmfKWqQOSFD0Gnzug4ALRgnHCShNDBcoRRAO7B3tC6tkGh4ZHRsQlJPg4BthKSBU4AJMD+TqhwcmzEAGLyAOYAdAqcEPFmAEIAwtRVAQD8+Nz8Qo4BhekARugwMASyiipqCnA+JLEAnmr4AAKy3gDWyhUwnDgKrQD6UHKSOM11cAAqEL19AL6l09MXK43MowVrNOAwCgAclmijgrS+UKo3yG-2cNjmCyWUD+aMmaPwSHwUAglxwUGaqJRU3RxVKAgA3ExqSAADQgCAAB1w0AUyFAOS6AAVYgg+Sg5Hx4nIdnz2bNCBoThCAMpyHhwAAy5LgyFQko28sVYGVMBVnI05OayBghHQcHZGx4OBtdodIDgAA9OeQcBrYJK3uQHoQcHBxfq+IaQAorXw4ABFdCk3VISPRgBWCk9KrjieT8D1BvdAEcC3AhVFOeL1ApglA4HAyCQ2SBbXIcHwrX0IDweHJkOo+HxW7GKfGzItQ-N4ELyNqG0Wo+7xnwAOpXeAKC1gOAqsU4XBPGA7QdgJStyT2gCSUDIsBVYFD3LMd5VJ-jS+jnKiGzXis5Qcf3DchJF1dlyQ2QgYErORmn7L93QtQgoMHWFZjgEd2R-ckYDXHASEuZAAA4AAZ2WIMscGIWD4IHNNi3ZGA5FmfDCM4ZAACZ2XQDY3hYiNGI9HgMJIZtNTkCl0DguAGggQh+0WK1BzkBYIBAb5viAA

```javascript
function render() {  
  return html`
    <div class="account">
      <h1>Account</h1>
      <div class="icon">
        <ui-chevron-arrow-icon></ui-chevron-arrow-icon>
      </div>
      ${
        featureFlag.showABC()
          ? html`
              <ui-button class="secondary" @click=${this._navigateToABC}>
                ${this.$t.get('base.ABC')}
              </ui-button>
            `
          : nothing
      }
    </div>
  `;
}

```

**Comment by dyc3** [comment]
Interesting, the biome playground shows an exact match with prettier, but the prettier playground definitely formats this differently.

**Comment by ematipico** [comment]
Probably a bug in the printer?

**Comment by ematipico** [comment]
What's the actual issue? In our playground, I see an exact match against prettier

**Comment by craftedsystems** [comment]
Prettier does a good job of formatting this code, as you can see on the Prettier playground. Biome does not format the code in the same way. Also, Prettier's output on the Biome playground does not show the same result as Prettier.
I see two problems:
1. Prettier output from Biome playground is different to actual output.
2. Biome formatting of this type of code produces unexpected results

**Comment by ah-yu** [comment]
> 1. Prettier output from Biome playground is different to actual output.

That's because different formatting configurations are used on the two sides. If you enable the `use-tabs` option and set the `embedded-language-formatting` option to `off` in the `Prettier` playground, you will achieve the same result as in the `Biome` playground.

[Prettier playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEATggCZyEAUAlPsPvgDpT3EzqHMAWMAtgDYADJvXoAeEjgBu+MHwCGAZwUBeBiDlhImGGoB8wkWM4BGXQEFNEbaID0J-c0P5xUmfKWqQOSFD0Gnzug4ALRgnHCShNDBcoRRAO7B3tC6tkGh4ZHRsQlJPg4BthKSBU4AJMD+TqhwcmzEAGLyAOYAdAqcEPFmAEIAwtRVAQD8+Nz8Qo4BhekARugwMASyiipqCnA+JLEAnmr4AAKy3gDWyhUwnDgKrQD6UHKSOM11cAAqEL19AL6l09MXK43MowVrNOAwCgAclmijgrS+UKo3yG-2cNjmCyWUD+aMmaPwSHwUAglxwUGaqJRU3RxVKAgA3ExqSAADQgCAAB1w0AUyFAOS6AAVYgg+Sg5Hx4nIdnz2bNCBoThCAMpyHhwAAy5LgyFQko28sVYGVMBVnI05OayBghHQcHZGx4OBtdodIDgAA9OeQcBrYJK3uQHoQcHBxfq+IaQAorXw4ABFdCk3VISPRgBWCk9KrjieT8D1BvdAEcC3AhVFOeL1ApglA4HAyCQ2SBbXIcHwrX0IDweHJkOo+HxW7GKfGzItQ-N4ELyNqG0Wo+7xnwAOpXeAKC1gOAqsU4XBPGA7QdgJStyT2gCSUDIsBVYFD3LMd5VJ-jS+jnKiGzXis5Qcf3DchJF1dlyQ2QgYErORmn7L93QtQgoMHWFZjgEd2R-ckYDXHASEuZAAA4AAZ2WIMscGIWD4IHNNi3ZGA5FmfDCM4ZAACZ2XQDY3hY8VbXtdk4B4DCSGbTU5ApdA4LgBoIEIftFitQcIFQVAQG+b4gA)

**Comment by craftedsystems** [comment]
The result is now the same - but still not at all what I would expect as output.

<img width="1276" alt="Screenshot 2024-06-03 at 09 31 37" src="https://github.com/biomejs/biome/assets/26137287/530aebe6-2fdb-4eb6-86d6-120193ce1d88">

**Comment by ematipico** [comment]
Biome doesn't support embedded formatting.
