### ISSUE TITLE
🐛 Different reporters give different count of issues

### ISSUE THREAD

**Issue by maximal** [biomejs/biome#3368]
### Environment information

```block
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.4.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.1.18"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

If I use `json` or `summary` reporter I see all issues, including issues on file naming conventions or import sorting:
```
$ bun node_modules/@biomejs/biome/bin/biome check --max-diagnostics=65535 resources/js/types/Task.ts

  ✖ Import statements could be sorted:
  
     1    │ - import·type·{·Project·}·from·'./Project';
     2    │ - import·type·{·Board·}·from·'./Board';
     3    │ - import·type·{·TaskStatus·}·from·'./TaskStatus';
     4    │ - import·type·{·User·}·from·'./User';
     5    │ - import·type·{·Change·}·from·'./Change';
     6    │ - import·type·{·TaskLink·}·from·'./TaskLink';
        1 │ + import·type·{·Board·}·from·'./Board';
        2 │ + import·type·{·Change·}·from·'./Change';
        3 │ + import·type·{·Project·}·from·'./Project';
        4 │ + import·type·{·TaskLink·}·from·'./TaskLink';
        5 │ + import·type·{·TaskStatus·}·from·'./TaskStatus';
        6 │ + import·type·{·User·}·from·'./User';
     7  7 │   
     8  8 │   export type Task = {
  

Checked 1 file in 31ms. No fixes applied.
Found 1 error.
```

If I use `github` reporter it skips these issues but returns code `1`:
```
$ bun node_modules/@biomejs/biome/bin/biome check --max-diagnostics=65535 --reporter=github resources/js/types/Task.ts

check ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Some errors were emitted while running checks.
  

error: "biome" exited with code 1
```

Somehow it is linked with issue location calculating, I guess (#3366 etc).

### Expected result

Here `github` reporter would calculate lines 1—6 (with corresponding columns), for example, and output those.

I don’t know what lines to output on filenaming issues, seems like even plain `1:1` is better than skip those issues entirely.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment]
The last time I checked it, the github reporter cannot get text ranges from the diagnostics that emitted from the formatter, because they don't set the `span` field so they don't get printed:
https://github.com/biomejs/biome/blob/9b64ad37535c8d60103bc11ebc1937ab568d779a/crates/biome_diagnostics/src/display_github.rs#L18-L28

IIRC we don't calculate text ranges in formatting, we only provide a diff result. So I'm not sure we can ever support them in these reporters.

I didn't check, but this issue about import sorting may have the same reason.

**Comment by maximal** [comment]
> IIRC we don't calculate text ranges in formatting, we only provide a diff result

@Sec-ant, yeah, the `"span"`s there (file naming, format, import sorting rules) are `null`ed. But I see an opportunity here to provide them also.

**Comment by Sec-ant** [comment]
> > IIRC we don't calculate text ranges in formatting, we only provide a diff result
> 
> @Sec-ant, yeah, the `"span"`s there (file naming, format, import sorting rules) are `null`ed. But I see an opportunity here to provide them also.

How do you think we can provide that? By extracting the `span` infos from the diff results?

And do you have any suggestions on how should we [annotate errors](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) about the file names in the GitHub actions? Because a file name doesn't have a line number or column number.

**Comment by maximal** [comment]
@Sec-ant

> How do you think we can provide that? By extracting the span infos from the diff results?
I don’t know how issue locations/spans are calculated currently, I did not examine Biome’s source code, unfortunately.
Seems like `AsDiagnostic` should be extended to have this information on format-related issues. I understand that currently a reported just gets span info from a diagnostic and does nothing more; maybe diagnostics should be more verbose on formatting issues. 

> And do you have any suggestions on how we should [annotate errors](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) about the file names in the GitHub actions
As I wrote in the beginning, concerning this:
> I don’t know what lines to output on filenaming issues, seems like even plain 1:1 is better than skip those issues entirely.

**Comment by Sec-ant** [comment]
Sorry that I missed your initial proposal.

**Comment by maximal** [comment]
Don’t worry. I understand that I can be vague (or maybe give impossible proposals) due to lack of understanding of Biome’s source code.

**Comment by nemchik** [comment]
I'm also seeing

```log
Run biome ci --reporter=github .
  biome ci --reporter=github .
  shell: /usr/bin/bash -e {0}
ci ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × Some errors were emitted while running checks.
  
Error: Process completed with exit code 1.
```

But I am not seeing any github comments. If I use `biome ci .` I do get output in the action log. Locally `biome ci --reporter=github .` produces the same output as the GH action.

I made a branch with intentional errors just to try using the github reporter. I mis-spelled one of the variables, and added a space somewhere I knew the formatter would fix (it removes the space when I run the formatter). Neither are showing up with the github reporter, but `biome ci --reporter=github .` exits with an error and no output, which is confusing and not helpful.

I don't know if the intention is to have \`\`\`suggest used in the github reporter (that would be really cool) but even if it's not, having no output indicating where to find the failures makes the github reporter pretty unusable in my testing.

For now I'm sticking to `biome ci .` so there can at least be something indicating why there is a failure. I hope this can get fixed soon. I'd love to actually see the github reporter working in action.

**Comment by maximal** [comment]
🎉
