### ISSUE TITLE
📎 New `--changed` argument

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#346]
### Description

Biome now has support for VCS, which means that we can unlock new features that make the life of developers easier!

One of these features is the addition of a new argument called --changed to the CLI. When we pass this argument, Biome will execute check/format/etc. only to those files that were changed.
## Technical details

I am still determining the implementation of this argument. There are two alternatives:

- execute the command via [Command](https://doc.rust-lang.org/std/process/struct.Command.html), we pass the proper arguments to the git program, and we read the output that was generated. Although I don't know yet what's the correct command/arguments to get an accurate output
 - Use the crate [git2](https://crates.io/crates/git2). While this crate is phenomenal, its size is not small (207kb)

What do you guys think?

**Comment by simonxabris** [comment]
I was a lerna user for long and I really like its [`--since`](https://lerna.js.org/docs/api-reference/commands#--since-ref) implementation. Basically you can provide any valid git ref to this command and it will roughly run the following git command: `git diff --name-only <ref provided by user>...HEAD`. This gives you the name of the files changed since that ref.

My proposal is this:

- Add a `vcs.defaultBranch` config option, where users specify the name for the default branch in their project.
- `--changed` will get the changes between `defaultBranch` and `HEAD` and only execute on those.

If there's no default branch configured, users will have to specify what they want to compare against with the CLI, for this we either:

- Add an optional argument to `--changed`, where they can specify a git ref to compare against, like `--changed main`
- Add a new argument called `--since` that does the same as above. Reason for this is imo `--since main` reads much better than `--changed main`.

Let me know what you think about this. If we can come to a conclusion on what to implement, I'm happy to contribute it!

**Comment by ematipico** [comment]
I love your proposal, I don't have anything to add! Feel free to take it and work on it. If you have any questions, just add a comment there and we'll try to answer

**Comment by simonxabris** [comment]
So as I'm implementing this, a couple of questions came up. My approach is based on how the gitignore files are handled. Basically I'm running the `git diff` command and extending (or creating) the `files.include` configuration field.

- First question, is this going to work or am I missing something?
- I've noticed the `check` command does not respect `files.include` field. If I have two files, `src/test.js` and `src/test2.js` and in the include field I specify `src/test.js`, when I run the CLI with the `src/*.js` pattern, the `check` command processes both files. The `lint` and `format` commands only process `src/test.js`. Is this a bug or is this intentional for some reason? If it's a bug I can file a new issue on this or I can just fix this as a part of this PR.

**Comment by ematipico** [comment]
> So as I'm implementing this, a couple of questions came up. My approach is based on how the gitignore files are handled. Basically I'm running the `git diff` command and extending (or creating) the `files.include` configuration field.
> 
>     * First question, is this going to work or am I missing something?

If with `files.include` you mean [the workspace settings](https://github.com/biomejs/biome/blob/891e726a21fd3930c602eb9fc70e0bf3638c8711/crates/biome_service/src/settings.rs#L36), then yes, it is going to work.

> 
>     * I've noticed the `check` command does not respect `files.include` field. If I have two files, `src/test.js` and `src/test2.js` and in the include field I specify `src/test.js`, when I run the CLI with the `src/*.js` pattern, the `check` command processes both files. The `lint` and `format` commands only process `src/test.js`. Is this a bug or is this intentional for some reason? If it's a bug I can file a new issue on this or I can just fix this as a part of this PR.

Our CLI doesn't support glob patterns as input. Doing `biome check ./src/*.js` will result in expected errors.

**Comment by simonxabris** [comment]
Thanks for confirming the first, that's what I meant!

On the second, I'm not so sure about that, obviously I may be misunderstanding something, but if I run this `biome check ./src/*.js`, this is the output I get:

<details>
<summary>Output of biome check ./src/*.js</summary>

<img width="384" alt="Screenshot 2023-11-15 at 19 34 04" src="https://github.com/biomejs/biome/assets/27497229/e765b7f7-dcf4-4aff-b88d-0727843413ba">

</details>

This is a regular installation of Biome, not some local version.

But regardless of the glob pattern, If I do `biome check ./src`, I'd still expect that only those files that are included by the `biome.json` `files.include` field will be checked, which is not the case as all files matched by the CLI input param are checked. This is a problem because my solution will not work for the `check` command. I'll create a separate issue with a reproduction so it can be discussed there.

**Comment by ematipico** [comment]
> On the second, I'm not so sure about that, obviously I may be misunderstanding something

Internally, we don't try to be smart; we take the paths passed by the CLI and convert them into `PathBuf`. We **don't** throw an error:

https://github.com/biomejs/biome/blob/73da2fdb91a7313e76fedbc644f831b74d06b3e7/crates/biome_cli/src/execute/traverse.rs#L248

Then, we rely on the information that `PathBuf` APIs give us.

**Comment by simonxabris** [comment]
I think I cracked what's going on. So based on my testing, glob patterns are actually accepted and the bug I mentioned about the `check` command handling more files what's in the `files.include` property only happen when a glob pattern is used as an input to the CLI.

<details>
<summary>Output of `check` and `lint` with a supported pattern and with a glob pattern</summary>

<img width="353" alt="Screenshot 2023-11-15 at 19 45 18" src="https://github.com/biomejs/biome/assets/27497229/5e1a73df-da9c-4ac9-aa03-2d4c16367748">

</details>

So i guess the real bug is that the CLI does not error if a glob pattern is provided. I'll file this as a separate issue.

**Comment by simonxabris** [comment]
> Internally, we don't try to be smart; we take the paths passed by the CLI and convert them into PathBuf. We don't throw an error

Oh I see, I just thought because you said `Doing biome check ./src/*.js will result in expected errors.` that I should've see an error using the CLI that way, but I didn't
