### ISSUE TITLE
📎 Implement `nursery/noDuplicateElseIf` - `eslint/no-dupe-else-if`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#40]
### Description

[no-dupe-else-if](https://eslint.org/docs/latest/rules/no-dupe-else-if/)

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by n-gude** [comment]
@victor-teles If you don't mind I would be happy to take this. I already done work on this since I commented in the regarding Rome issue. Sorry that I didn't reached out earlier.

@ematipico @Conaclos I would propose a name like `noUnreachableBranch` since this is essentially what this rule detects. 
I would also like to extend the rule to cover (almost) all boolean algebra. The Eslint rule covers only some cases depending on `&&` and `||`. Boolean algebra rules like Distributive and DeMorgan aren't handled.

**Comment by Conaclos** [comment]
> I would propose a name like noUnreachableBranch since this is essentially what this rule detects.

I am not sure that it is the same rule.
For example, `noUnreachableBranch` could accept the following code, while `noDuplicateElseIf` reports the code:

```js
if (check(x)) {
    foo();
} else if (check(x)) {
    bar();
}
```

Thinking more about this code, I think this could be good to accept it?

Also, should the rule report cases as follows:

```js
if (false) { /* unreachable */ }

if (true) {} else { /* unreachable */ }

while (false) {}
```

I also wonder if `noUnreachableBranch` should be integrated in [noUnreachable](https://biomejs.dev/linter/rules/no-unreachable).

**Comment by ematipico** [comment]
This was never addressed. If anyone wants to take, feel free

**Comment by chansuke** [comment]
I'd like to work on this issue.

**Comment by ematipico** [comment]
I removed @chansuke due to inactivity. If someone wants to give it a shot, you could cherry-pick https://github.com/biomejs/biome/pull/1758 :)

**Comment by chansuke** [comment]
@ematipico 
Oh, sorry for my inactivity...
I was too busy for my work.
Ok, thank yo so much for your support.

**Comment by mdm317** [comment]
Can i try this issue?

**Comment by Conaclos** [comment]
> Can i try this issue?

You are welcome!
