### ISSUE TITLE
🐛 Ignoring `biome.json` configuration

### ISSUE THREAD

**Issue by max-sym** [biomejs/biome#4038]
### Environment information

```block
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.8.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/9.10.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. Have VS Code as your IDE
1. Add biome extension
1. Create a pnpm monorepo project
1. Add biome.json at the root with the following contents:
```

{
  "$schema": "https://biomejs.dev/schemas/1.8.3/schema.json",
  "organizeImports": {
    "enabled": true
  },
  "files": {
    "ignore": ["__generated__/*", "assets/*", ".vercel/*", "dist"]
  },
  "formatter": {
    "enabled": true,
    "formatWithErrors": false,
    "ignore": [],
    "attributePosition": "auto",
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 80,
    "lineEnding": "lf"
  },
}
```
5. Notice that it ignores this config file when you save the files (for instance, it adds `;` at the end of all code lines even though it's instructed in the configuration to avoid doing that.

NOTE:
- It happens randomly - when I reload VS Code it usually doesn't go away, but when I restart the Mac it might work. It's 50/50. I haven't noticed any specific patter to make it work / not work.

A few ideas:
- Maybe it's due to using a pnpm workspaces architecture?
- Maybe it's due to having open multiple projects in VS Code?

### Expected result

It should format the files according to the config file every time it's in the correct VS Code project / workspace / folder.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by max-sym** [comment]
PS:
Seems like it's working after I save the file twice. Related issues:
- https://github.com/fannheyward/coc-biome/issues/13
- https://github.com/biomejs/biome/issues/1556
- https://github.com/fannheyward/coc-biome/issues/21
- https://github.com/biomejs/biome/issues/2228

**Comment by ematipico** [comment]
That's expected. Since you installed the extension first, the extension uses the bundled version with the defaults. Even after you add the configuration file, you would need to remove the bundled version. 

Generally, it's advice to install the CLI first, and then open the editor and install the extension

**Comment by ematipico** [comment]
> Why is the bundled version not looking for the config file though?
> 
> Also even if this is expected, it is not intuitive at all

It **should** look for the configuration file. The issue here was different. OP created the configuration file **after** the extension started. The extension, when it starts, it starts a server that looks for the configuration file, but if it doesn't find it, it uses its defaults. 

If you create a configuration file after the server started, you'll need to restart the server. I believe that's a limitation of the client that can't watch files that are created **after** the service starts.

**Comment by vdawg-git** [comment]
Ah, yes I see. My bad, I should have read it more carefully. 

Thank you for clarifying :)
