### ISSUE TITLE
Problem in extensions vscode

### ISSUE THREAD

**Issue by pageton** [biomejs/biome#4318]
### Environment information

```block
There is a problem with the vscode extension. When I install it, it does not work and does not serve any purpose. I tried all the methods and it also did not work. Only when I modified it did it work and I sent a pr and it was rejected.
```

### What happened?

.

### Expected result

.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Hey @pageton 

I looked at the PR, and I understand why the maintainer closed the PR: there's little context, there's no so issue that explains the issue, and there's no way to reproduce it.

My advice is to look for closed/open issues, maybe the issue was already solved. 

If you can't find it, open a bug report  in the extension repository, with a reproduction or instructions to have a predictable way. Without a reproduction, your bug report will be rejected.
