### ISSUE TITLE
🐛 Error: Cannot find module '@biomejs/cli-linux-x64/biome' on x64 linux host

### ISSUE THREAD

**Issue by Lornz-** [biomejs/biome#4467]
### Environment information

```block
CLI:
  Version:                      1.9.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.2.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

I just got the exact same issue as described in #3804 during the build running on a x64 linux host. I tried to bump the **1.8.3** version to a newer one **1.9.x** but I still have the same error `Error: Cannot find module '@biomejs/cli-linux-x64/biome'`. Is that something I missing?

### Expected result

It should work as intended.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Lornz-** [comment]
Well it's kind of hard to reproduce since it only happens at build time on a x86 linux host. Everything's fine otherwise.

**Comment by ematipico** [comment]
PR welcome. The person of the other issue identified the bug and the solution

**Comment by elawad** [comment]
@mrabdibdi-anvil We use Biome in GitHub Actions w Ubuntu as well. No issues there using Biome 1.9.2.

Perhaps your npm/yarn lock file needs to be deleted, and re-install. Could be due to different architectures between your PC and the Actions environment.

Ran into a similar issue before, using the Sharp js library.

**Comment by Lornz-** [comment]
Hi there! Apologies for the delayed response. it’s been a crazy week.

It turns out I was mistaken about the error. it wasn't directly related to the issue itself or caused by Biome. The problem stemmed from conflicts in my lock file after adding new dependencies. I'm not entirely sure what went wrong, but I resolved it by checking out the lock file from the main branch, performing a clean install, and then re-installing the new dependencies.

**Comment by ItsWendell** [comment]
What did you do to fix this? I'm running Fedora 41, when I install biomejs for some reason it doesn't load or install the binaries, so I'm getting the same error. On other projects I've never had to deal with this in other projects though we share the same settings, possibly due to the binary already there from previous versions? @Lornz- 

I use bun, so when I delete node_modules folder and I run biome through bunx, for example `bunx @biomejs/biome check --write .`, it works perfectly fine, when I then run `bun install` and after I run it again `bunx @biomejs/biome check --write .` I get the same error.

**Comment by okineadev** [comment]
As `@ematipico` [said](https://github.com/biomejs/biome/issues/4660#issuecomment-2508201015) to me in #4660:

> It's possible that `bun` isn't installing the optional dependencies for your OS, in particular the package `@biomejs/cli-linux-x64`. Package managers usually install the optional dependencies themselves, but this doesn't seem to be the case in your case.
> 
> I would file an issue with Bun at this point, because other package managers don't have this issue.
> 
> As a workaround, you can install the dependency yourself:
> 
> ```
> bun install @biomejs/cli-linux-x64
> ```

**Comment by okineadev** [comment]
> Hello,
> 
> i have this issue with Github Action using Ubuntu-latest and nodejs 20
> 
> 1. Tried using the `package.json` (works locally, with turbo and with docker on macos)
> 2. Tried using explicit `npx @biomejs/biome ...` (show the error on github action, works on macos)
> 3. Tried installing globally `npm install -g @biomejs/biome@1.9.0` (show the error on github action)

I found a workaround for the following problem: https://github.com/okineadev/okineadev-website/blob/908bf907cfa9e4260d0367747af77ec210a7563e/.github/workflows/static.yml#L52-L53

**Comment by sourcesoft** [comment]
i fixed it by removing my node_modules folder `rm -rf node_modules` and tried again.

**Comment by ematipico** [comment]
> For me the problem was, that someone with a different OS installed biome. Now when I just run `npm install`, it will only install the dependencies according to the package-lock.json, which only includes the optional dependencies for my colleague's OS, and not my own. I needed to reinstall biome, and then commit the changes of package-lock.json: `npm i -D @biomejs/biome@latest`

This seems a `npm` bug, you should consider filing an issue.

**Comment by okineadev** [comment]
My solution is to simply install `@biomejs/biome` in the project

**Comment by uta-bogle** [comment]
I landed here with the same issue in a github action. My solution was to forcefully install the linux cli and then remove it from my package.json.

Basically,

```bash
npm i -D --force @biomejs/cli-linux-x64
```

Then remove the `@biomejs/cli-linux-x64` dev dependency from package.json and the deps list at the top of the package lock which resulted in the linux cli being properly listed as an optional dependency only in the package lock.

**Comment by mikaello** [comment]
With version [v2.2.7](https://github.com/biomejs/biome/releases/tag/%40biomejs%2Fbiome%402.2.7) (v2.2.6 works) of Biome I get the same error, and [the fix](https://github.com/biomejs/biome/issues/4467#issuecomment-3353320381) by @uta-bogle does work, but is not acceptable in the long run. For example, what happens when Renovate (or Dependabot) tries to update Biome later on, and how to maintain the version of `@biomejs/cli-linux-x64`?

**Comment by uta-bogle** [comment]
For what it's worth @mikaello after I posted this I did end up with a better "fix" based on this note above,

> This seems a npm bug, you should consider filing an issue.

Which led me to this [npm/cli issue](https://github.com/npm/cli/issues/7961) for npm v10. So I upgraded to npm v11 and haven't had the problem since. Also FYI, from [the PR thread](https://github.com/npm/cli/pull/8184) it looks like the [fix won't be back-ported](https://github.com/npm/cli/pull/8184#issuecomment-2817193156).

**Comment by mikaello** [comment]
Thanks! NPM v11 fixed the problem! 😸

**Comment by seguri** [comment]
I'm currently developing my project on multiple platforms. My laptop is running on Windows, but I also run claude code in a docker sandbox, which runs on linux. The result is that if I install biome under Windows, I can format and lint the code, but claude code can't because in the sandbox it throws `Error: Cannot find module '@biomejs/cli-linux-x64/biome'`. How do you suggest to fix this? Consider that any solution that requires global installs will fail, because the sandbox won't have access to those tools. Example: can't use pnpm
