### ISSUE TITLE
🐛 aarch64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found 

### ISSUE THREAD

**Issue by GiancarlosIO** [biomejs/biome#530]
### Environment information

```block
OS: linux-arm64
@biomejs/biome: "1.2.2
```
(i can't run `biome rage` because it fails with the same error)

### What happened?

Hi there
I'm experiencing the following error in CI using linux-arm64 when running `biome check .` 😢

````bash
@my-app/cli:lint: /builds/my-team/frontend/team-frontend-apps/node_modules/.pnpm/@biomejs+cli-linux-arm64@1.2.2/node_modules/@biomejs/cli-linux-arm64/biome: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /builds/my-team/frontend/team-frontend-apps/node_modules/.pnpm/@biomejs+cli-linux-arm64@1.2.2/node_modules/@biomejs/cli-linux-arm64/biome)
. prepare: @my-app/cli:lint:  ELIFECYCLE  Command failed with exit code 1.
````

Thanks

### Expected result

It should check the files without errors

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Unfortunately we don't support Tier 2 platforms yet :(

https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-with-host-tools

We would like to support some of them, but unfortunately we don't have the knowledge and bandwidth to do so. It would be great if someone else would help in achieving that.

**Comment by faultyserver** [comment]
We ran into a similar issue initially trying to get biome to run in our CI and the root of the issue is that the binary is compiled on a version of linux that's newer than where it's trying to be run. In this case, it seems like biome is being compiled on an OS with `GLIBC_2.29` as a minimum target, but your OS most likely has an older version like 2.28 or less.

### Context

If you take a look at the [glibc timeline](https://sourceware.org/glibc/wiki/Glibc%20Timeline), you can see that glibc 2.29 was released in 2019. Most linux distributions then started shipping with it as the baseline soon after, like Ubuntu 20.04 (released in 2020), Debian 11 (released in 2021), and so on.

Nowadays, even the previous LTS versions of those OSes are now end-of-life (ubuntu 18.04 in april 2023, debian 10 in june 2022), and most CI providers and other vendors are no longer allowing new VMs to be created with those old OSes.

### Diagnosing

You can figure out which version of glibc your OS has installed by running `ldd --version`. You'll get an output like:
```
$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.4) 2.35
```
Here, I'm on ubuntu 22.04, released last year, with glibc 2.35.

If your result from this command is something _higher_ than glibc 2.29, then there may be another issue causing your system to resolve glibc differently or possibly something else even more obtuse.

### Resolution

glibc is not a package that you can really upgrade without doing a full OS upgrade. You _can_, but it's really not recommended as it can break a lot of core system functionality.

Since (almost) all of the OSes that ship with glibc < 2.29 are now end of life, the best thing to consider is upgrading your OS to a still-supported LTS version, any of which nowadays _should_ have a newer glibc and thus be able to run biome as expected (or at least solve this specific error).

The other option is that Biome could intentionally build versions of the package with an old OS, but again, since they are no longer supported, I [don't think GitHub Actions will even let you build on an old enough version of linux anymore](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/). Even if the package was built for the target architecture, the lack of a newer glibc version would still cause this error to come up.

**Comment by GiancarlosIO** [comment]
@faultyserver Thanks so much for the detailed explanation. I'll talk with our infra team to try to upgrade the so version that we are using in our CI.

Thanks again!

**Comment by axieum** [comment]
Unfortunately, if you're using dynamic Jenkins agents, you'll need to wait for a RHEL 9 image before you can use this project in your CI.

For this reason, we've had to drop Biome JS until https://github.com/openshift/jenkins/issues/1766 is resolved.

**Comment by johnpyp** [comment]
This could also potentially be addressed by using a container overlay like is used for `manylinux` that has an older version of glibc, see this blog post about a similar solution: https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html

Alternatively, building with musl and routing based on the system glibc might work?

**Comment by johnpyp** [comment]
What swc does here should actually be quite portable - They use the official `napi-rs` images (e.g [here](https://github.com/swc-project/swc/blob/main/.github/workflows/publish-npm-package.yml#L134) in their build action). The `napi-rs` [image uses manylinux](https://github.com/napi-rs/napi-rs/blob/main/debian.Dockerfile) itself for maximum compatibility
