### ISSUE TITLE
Rebrand the homepage

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#882]
Requirements:
- logo with brand
- sponsors 

Ideas?

**Comment by 11Firefox11** [comment]
Just as a quick idea:
I like the speed comparison that [esbuild has on their homepage](https://esbuild.github.io/). I think something like this should be included (compare speed with Prettier).

**Comment by ematipico** [comment]
Here's an example of what Rome had: https://web.archive.org/web/20230203060333/https://rome.tools/

**Comment by vasucp1207** [comment]
Can I work on this one?

**Comment by ematipico** [comment]
> Just as a quick idea:
> I like the speed comparison that [esbuild has on their homepage](https://esbuild.github.io/). I think something like this should be included (compare speed with Prettier). 

Yeah it would be great to have some speed comparison. I believe Prettier should be the easier to benchmark.

Also, we should also consider other benchmarks, like eslint. That will take more time to prepare, but still to consider for a future graph.

**Comment by ematipico** [comment]
> Can I work on this one?

I think we should first collect some ideas, to understand how we want to design the homepage. Do you have some? Can you share some prototypes first?

**Comment by vasucp1207** [comment]
> > Can I work on this one?
> 
> I think we should first collect some ideas, to understand how we want to design the homepage. Do you have some? Can you share some prototypes first?
Sure, I will share a prototype showing benchmark progress bar comparison.

**Comment by Conaclos** [comment]
We should also highlight our compatibility score with Prettier. Saying that we support TypeScript JavaScript, and JSON.

We could also demonstrate the linter experience on a console and on an editor via a short animation / auto-play video.

**Comment by Conaclos** [comment]
> Here's an example of what Rome had: https://web.archive.org/web/20230203060333/https://rome.tools/

I like the Rome home page. It feels better than the one we currently have.

**Comment by vasucp1207** [comment]
Here is my first attempt,

![biome2](https://github.com/biomejs/biome/assets/85363195/b37e0b2d-6aa2-43c0-b49f-460a0c95207e)

**Comment by ematipico** [comment]
That's an amazing start! 

I think we could break down the changes as follow:
- hero with the new logo
- performance section
- code contributors

The new top bar isn't part of this attempt yet. 


Are the numbers of the performance section made up for now?

**Comment by ardunster** [comment]
A couple of suggestions, as I was just on your website as someone potentially interested in using the tool.

The website as it is right now is utterly uninformative. There are two buttons, one to get started installing the tool (which I don't want to do without understanding it far better than I do now), and one to come to GitHub. Otherwise, there are just a few blurbs about how good the product is, but almost nothing about *what* it is, how it is supposed to work, or - what I was most interested in - guidance on how how difficult or complicated it might be to transfer existing configuration from tools such as Prettier and ESLint, compatibility with those configs (I'm curious about compatibility especially with the plethora of ESLint plugin rulesets), and so on. As it is, I have no idea if I could just input my existing rules and configs into a new tool and have speed benefits, or if I'd have to go through a bunch of setup to maintain my existing rules, or whether or not it's even possible to have the same set of ESLint rules that one has on a mature project. 

If you're redesigning the landing page for this tool, I'd strongly suggest including a section with a brief description of what the tool actually is and does, ideally with a link to a more in depth explanation that is *not* just "here's how you install it!", and a section hitting the highlights of how the rule config compares to Prettier, ESLint, etc and whether or not users will have to learn a new config pattern, obtain new plugins or sets of lint rules, etc., also with a link to a page that goes more in depth.

As it is now, I have no idea if I want to use this tool, what the benefits would be over the existing tools I'm used to, or what the drawbacks would be in making the switch.

**Comment by vasucp1207** [comment]
<details>
<summary>Rome's like section,</summary>


https://github.com/biomejs/biome/assets/85363195/38b3e0a3-3423-48b2-9289-0ecaf94ccec5


</details>

I thind this one is more better and gives a clear idea.

**Comment by ematipico** [comment]
@vasucp1207 What do you think of [**this variant**](https://docs-git-fork-theotterlord-starlight-migration-astrodotbuild.vercel.app/en/getting-started/)? Just as an example. I think Rome's old comparisons are valid, let's try to not be very aggressive though.

Feel free to start sending some PR, maybe with the new contributors section :) I liked it a lot

**Comment by vasucp1207** [comment]
Sure, I like the new astro website and will be taking some design inspiration from it.

**Comment by ematipico** [comment]
Closing! This is done for now, but we are always looking for suggestions and improvements!
